Update+ improvements  Usagesummary.ps1
Azure/AzureStack-Tools pull request #591
Opened 2021-01-12 10:52 UTC by CarlosGon

Added 3 missing metrics.
Changed the logic for retrieving usage:
. Created an array with the list of all subscriptions
. Changed the get-azsSubscriberUsage to include the subscriberID. 
This way we will have better performance, avoiding gateway timeout errors while executing the sql query.

2021-03-05 17:42 UTC, CarlosGon commented
any feedback on this?

2021-03-10 13:15 UTC, CarlosGon commented
#sign-off

2021-05-13 13:57 UTC, CarlosGon commented
any update on this PR?

2021-05-13 14:12 UTC, cblackuk requested changes
Good changes, but need a few tiny fixes - IMHO :-)

2021-05-13 14:12 UTC, cblackuk commented on Usage/Usagesummary.ps1
> +    'Custom Worker Tiers' = 'Custom Worker Tiers Unit: Hours'
Can you format this please? :-)

2021-05-13 14:12 UTC, cblackuk commented on Usage/Usagesummary.ps1
> +$subtable = New-Object System.Collections.ArrayList
Why?

2021-05-13 14:12 UTC, cblackuk commented on Usage/Usagesummary.ps1
> +        [void]($usageSummary.Add([pscustomobject] @{
Can you format doc in VSCode to make it a little more readable?

2021-05-13 14:12 UTC, cblackuk commented on Usage/Usagesummary.ps1
> +        $resourceInfo = ($entry.InstanceData | ConvertFrom-Json).'Microsoft.Resources'
Can you format doc in VSCode to make it a little more readable?

2021-06-21 07:59 UTC, pappleby64 approved these changes
Look like good changes - agree with other comments

2021-12-07 19:48 UTC, bganapa commented
@CarlosGon could you pls address the comments? Can you pls make the PR to the az branch as well?

2021-12-10 16:21 UTC, CarlosGon commented
@bganapa 
Comments resolved. Code formatted with VScode

2021-12-10 19:06 UTC, merged